project_id = "delos"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-customer-portal]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.sync-revenuecat-entitlement]
verify_jwt = true

[functions.push-notifications]
verify_jwt = false
