create extension if not exists pgcrypto;
create type public.skill_level as enum ('Developing','Intermediate','Advanced','Professional');
create type public.commitment_level as enum ('Casual','Consistent','Serious','Professional');
create type public.proposal_status as enum ('pending','accepted','declined');

create table public.users (id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.musician_profiles (user_id uuid primary key references public.users(id) on delete cascade, display_name text not null check (char_length(display_name) between 2 and 50), age int not null check (age between 18 and 100), general_location text not null, bio text not null default '' check (char_length(bio)<=500), primary_instrument text not null, desired_roles text[] not null default '{}', skill public.skill_level not null, years_experience int not null default 0 check(years_experience between 0 and 80), commitment public.commitment_level not null, goals text[] not null default '{}', material text not null check(material in ('Originals','Covers','Both')), rehearsal_frequency text not null default 'Weekly', travel_radius_km int not null default 40 check(travel_radius_km between 1 and 250), transportation boolean not null default false, performance_ready_gear boolean not null default false, existing_band text, public_links jsonb not null default '[]', verified_email boolean not null default false, available_now boolean not null default false, discovery_visible boolean not null default true, last_active_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.instruments (id bigint generated always as identity primary key, name text unique not null);
create table public.profile_instruments (profile_id uuid references public.musician_profiles(user_id) on delete cascade, instrument_id bigint references public.instruments(id), is_primary boolean not null default false, primary key(profile_id,instrument_id));
create table public.genres (id bigint generated always as identity primary key, name text unique not null);
create table public.profile_genres (profile_id uuid references public.musician_profiles(user_id) on delete cascade, genre_id bigint references public.genres(id), primary key(profile_id,genre_id));
create table public.influences (id uuid primary key default gen_random_uuid(), profile_id uuid references public.musician_profiles(user_id) on delete cascade, name text not null);
create table public.availability (id uuid primary key default gen_random_uuid(), profile_id uuid references public.musician_profiles(user_id) on delete cascade, day_of_week int not null check(day_of_week between 0 and 6), period text not null check(period in ('Morning','Afternoon','Evening')), unique(profile_id,day_of_week,period));
create table public.media_samples (id uuid primary key default gen_random_uuid(), profile_id uuid references public.musician_profiles(user_id) on delete cascade, media_type text not null check(media_type in ('image','audio','video')), storage_path text not null, title text not null, mime_type text not null, size_bytes bigint not null check(size_bytes>0), sort_order int not null default 0, created_at timestamptz not null default now());
create table public.discovery_preferences (user_id uuid primary key references public.users(id) on delete cascade, max_distance_km int not null default 50 check(max_distance_km between 1 and 250), age_min int not null default 18 check(age_min>=18), age_max int not null default 100 check(age_max>=age_min), instrument_ids bigint[] not null default '{}', genre_ids bigint[] not null default '{}', goals text[] not null default '{}', commitments public.commitment_level[] not null default '{}', notifications_muted boolean not null default false, updated_at timestamptz not null default now());
create table public.likes (actor_id uuid references public.users(id) on delete cascade, target_id uuid references public.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(actor_id,target_id), check(actor_id<>target_id));
create table public.passes (actor_id uuid references public.users(id) on delete cascade, target_id uuid references public.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(actor_id,target_id), check(actor_id<>target_id));
create table public.matches (id uuid primary key default gen_random_uuid(), user_a uuid references public.users(id) on delete cascade, user_b uuid references public.users(id) on delete cascade, created_at timestamptz not null default now(), check(user_a<user_b), unique(user_a,user_b));
create table public.conversations (id uuid primary key default gen_random_uuid(), match_id uuid unique references public.matches(id) on delete cascade, created_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid references public.conversations(id) on delete cascade, sender_id uuid references public.users(id) on delete cascade, body text not null check(char_length(body) between 1 and 2000), created_at timestamptz not null default now(), read_at timestamptz);
create table public.session_proposals (id uuid primary key default gen_random_uuid(), conversation_id uuid references public.conversations(id) on delete cascade, proposer_id uuid references public.users(id) on delete cascade, kind text not null check(kind in ('Rehearsal','Audition')), starts_at timestamptz not null, general_location text not null, songs text[] not null check(cardinality(songs)=3), status public.proposal_status not null default 'pending', responded_at timestamptz, created_at timestamptz not null default now());
create table public.blocks (blocker_id uuid references public.users(id) on delete cascade, blocked_id uuid references public.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(blocker_id,blocked_id), check(blocker_id<>blocked_id));
create table public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid references public.users(id) on delete cascade, reported_id uuid references public.users(id) on delete cascade, reason text not null, details text not null default '' check(char_length(details)<=1000), status text not null default 'open', created_at timestamptz not null default now(), check(reporter_id<>reported_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.users(id) on delete cascade, kind text not null, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.subscription_status (user_id uuid primary key references public.users(id) on delete cascade, tier text not null default 'free' check(tier in ('free','amplified')), provider text, provider_customer_id text, expires_at timestamptz, updated_at timestamptz not null default now());

create index messages_conversation_created_idx on public.messages(conversation_id,created_at);
create index profiles_active_idx on public.musician_profiles(last_active_at desc) where discovery_visible;
create index likes_target_idx on public.likes(target_id,created_at);
create index notifications_user_idx on public.notifications(user_id,created_at desc);
create index blocks_blocked_idx on public.blocks(blocked_id);

alter table public.users enable row level security; alter table public.musician_profiles enable row level security; alter table public.discovery_preferences enable row level security; alter table public.likes enable row level security; alter table public.passes enable row level security; alter table public.matches enable row level security; alter table public.conversations enable row level security; alter table public.messages enable row level security; alter table public.session_proposals enable row level security; alter table public.blocks enable row level security; alter table public.reports enable row level security; alter table public.notifications enable row level security; alter table public.subscription_status enable row level security; alter table public.profile_instruments enable row level security; alter table public.profile_genres enable row level security; alter table public.influences enable row level security; alter table public.availability enable row level security; alter table public.media_samples enable row level security;

create policy "profiles visible to members" on public.musician_profiles for select to authenticated using (discovery_visible or user_id=auth.uid());
create policy "own profile insert" on public.musician_profiles for insert to authenticated with check(user_id=auth.uid()); create policy "own profile update" on public.musician_profiles for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own user row" on public.users for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "own preferences" on public.discovery_preferences for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own likes read" on public.likes for select to authenticated using(actor_id=auth.uid()); create policy "own likes insert" on public.likes for insert to authenticated with check(actor_id=auth.uid());
create policy "own passes" on public.passes for all to authenticated using(actor_id=auth.uid()) with check(actor_id=auth.uid());
create policy "participant matches" on public.matches for select to authenticated using(auth.uid() in (user_a,user_b));
create policy "participant conversations" on public.conversations for select to authenticated using(exists(select 1 from public.matches m where m.id=match_id and auth.uid() in (m.user_a,m.user_b)));
create policy "participant messages read" on public.messages for select to authenticated using(exists(select 1 from public.conversations c join public.matches m on m.id=c.match_id where c.id=conversation_id and auth.uid() in (m.user_a,m.user_b)));
create policy "participant messages insert" on public.messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.conversations c join public.matches m on m.id=c.match_id where c.id=conversation_id and auth.uid() in (m.user_a,m.user_b)));
create policy "participant proposals" on public.session_proposals for select to authenticated using(exists(select 1 from public.conversations c join public.matches m on m.id=c.match_id where c.id=conversation_id and auth.uid() in (m.user_a,m.user_b))); create policy "proposer inserts" on public.session_proposals for insert to authenticated with check(proposer_id=auth.uid());
create policy "own blocks" on public.blocks for all to authenticated using(blocker_id=auth.uid()) with check(blocker_id=auth.uid());
create policy "own reports insert" on public.reports for insert to authenticated with check(reporter_id=auth.uid());
create policy "own notifications" on public.notifications for select to authenticated using(user_id=auth.uid()); create policy "own notifications update" on public.notifications for update to authenticated using(user_id=auth.uid());
create policy "own subscription" on public.subscription_status for select to authenticated using(user_id=auth.uid());

do $$ declare t text; begin foreach t in array array['profile_instruments','profile_genres','influences','availability','media_samples'] loop execute format('create policy "profile child read %1$s" on public.%1$I for select to authenticated using (exists(select 1 from public.musician_profiles p where p.user_id=profile_id and (p.discovery_visible or p.user_id=auth.uid())))',t); execute format('create policy "profile child own %1$s" on public.%1$I for all to authenticated using(profile_id=auth.uid()) with check(profile_id=auth.uid())',t); end loop; end $$;

create or replace function public.create_like_and_match(target_user_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare a uuid:=auth.uid(); low_id uuid; high_id uuid; match_id uuid; begin if a is null or a=target_user_id then raise exception 'invalid like'; end if; if exists(select 1 from blocks where (blocker_id=a and blocked_id=target_user_id) or (blocker_id=target_user_id and blocked_id=a)) then raise exception 'blocked'; end if; insert into likes(actor_id,target_id) values(a,target_user_id) on conflict do nothing; if not exists(select 1 from likes where actor_id=target_user_id and target_id=a) then return null; end if; low_id:=least(a,target_user_id); high_id:=greatest(a,target_user_id); insert into matches(user_a,user_b) values(low_id,high_id) on conflict(user_a,user_b) do update set user_a=excluded.user_a returning id into match_id; insert into conversations(match_id) values(match_id) on conflict(match_id) do nothing; return match_id; end $$;
revoke all on function public.create_like_and_match(uuid) from public; grant execute on function public.create_like_and_match(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('profile-media','profile-media',false,104857600,array['image/jpeg','image/png','image/webp','audio/mpeg','audio/mp4','audio/wav','video/mp4','video/quicktime']) on conflict do nothing;
create policy "members read profile media" on storage.objects for select to authenticated using(bucket_id='profile-media'); create policy "users upload own media" on storage.objects for insert to authenticated with check(bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text); create policy "users manage own media" on storage.objects for update to authenticated using(bucket_id='profile-media' and owner_id=auth.uid()::text); create policy "users delete own media" on storage.objects for delete to authenticated using(bucket_id='profile-media' and owner_id=auth.uid()::text);
